# scraped from following url:           https://forum.effectivealtruism.org/tags/all
# using this regex on each html list:   ">([a-zA-Z\s]*)<

# Note that not all categories on the webpage are included here. pull requests to add missing welcome.

global_poverty = ["Aid and paternalism",
"Burden of disease",
"Cash transfers",
"Deworming",
"Economic growth",
"Education",
"Family planning",
"Foreign aid",
"Foreign aid skepticism",
"Global health and wellbeing",
"Global poverty",
"Immigration reform",
"Malaria",
"Micronutrient programs",
"Research into neglected tropical diseases",
"Smallpox Eradication Programme",
"Tobacco control",
"Universal basic income"]

animal_welfare = ["Animal product alternatives",
"Crustacean welfare",
"Cultured meat",
"Dietary change",
"Farmed animal welfare",
"Fish welfare",
"Invertebrate welfare",
"Logic of the larder",
"Speciesism",
"Welfare biology",
"Wild animal welfare"]

ai = ["AI alignment",
"AI boxing",
"AI ethics",
"AI forecasting",
"AI race",
"AI safety",
"AI skepticism",
"AI takeoff",
"AI winter",
"Alignment tax",
"Anthropic capture",
"Artificial intelligence",
"Artificial sentience",
"Basic AI drive",
"Capability control method",
"Collective superintelligence",
"Comprehensive AI Services",
"Computation hazard",
"Economics of artificial intelligence",
"Governance of artificial intelligence",
"Indirect normativity",
"Infrastructure profusion",
"Instrumental convergence thesis",
"Intelligence explosion",
"Malignant AI failure mode",
"Mind crime",
"Motivation selection method",
"Oracle AI",
"Orthogonality thesis",
"Perverse instantiation",
"Quality superintelligence",
"Sovereign AI",
"Speed superintelligence",
"Superintelligence",
"Tool AI",
"Whole brain emulation"]

catastrophic_risks = ["Asteroids",
"Biosecurity",
"Biosurveillance",
"Civilizational collapse",
"Cuban Missile Crisis",
"Climate change",
"Climate engineering",
"Conservation",
"Dystopia",
"Existential risks from fundamental physics research",
"Geomagnetic storms",
"Great power conflict",
"Human extinction",
"Manhattan Project",
"Nuclear disarmament movement",
"Nuclear security",
"Nuclear warfare",
"Nuclear winter",
"Pandemic preparedness",
"Terrorism",
"Trinity",
"Supervolcano",
"Weapons of mass destruction"]

ea_meta = [
"Altruistic motivation",
"Building effective altruism",
"Community",
"Competitive debating",
"Consultancy",
"Effective altruism education",
"Effective altruism groups",
"Effective altruism in the media",
"Effective altruism messaging",
"Effective altruism outreach in schools",
"Event strategy",
"Field building",
"Fundraising",
"Global outreach",
"Moral advocacy",
"Movement collapse",
"Network building",
"Public giving",
"Request for proposal",
"Scalably using labour",
"Teaching materials",
"Value drift",
"Value of movement growth"]

other_causes = [
"Aging research",
"Air pollution",
"Armed conflict",
"Autonomous weapon",
"Cause candidates",
"Cause X",
"Cluster headache",
"Cognitive enhancement",
"Criminal justice reform",
"Electoral reform",
"Global priorities research",
"Land use reform",
"Local priorities research",
"Mental health",
"Moral circle expansion",
"Research",
"Risks from malevolent actors",
"Space colonization"]


moral_philosophy = [
    "Animal cognition",
    "Animal sentience",
    "Applied ethics",
    "Astronomical waste",
    "Axiology",
    "Bioethics",
    "Classical utilitarianism",
    "Cluelessness",
    "Consciousness research",
    "Consequentialism",
    "Cosmopolitanism",
    "Demandingness of morality",
    "Deontology",
    "Ethics of existential risk",
    "Ethics of personal consumption",
    "Future of humanity",
    "Hedonism",
    "Hedonium",
    "Infinite ethics",
    "Introspective hedonism",
    "Intuition of neutrality",
    "Longtermism",
    "Metaethics",
    "Moral offsetting",
    "Moral patienthood",
    "Moral uncertainty",
    "Moral weight",
    "Negative utilitarianism",
    "Normative ethics",
    "Normative uncertainty",
    "Other moral theories",
    "Pain and suffering",
    "Patient altruism",
    "Personal identity",
    "Philosophy of mind",
    "Population ethics",
    "Prioritarianism",
    "Sentience",
    "Subjective wellbeing",
    "Utilitarianism",
    "Valence",
    "Virtue ethics",
    "Welfarism",
    "Wellbeing",
]

long_term_risks_and_flourising = [
    "Alternative food",
    "Anthropogenic existential risk",
    "Anthropic shadow",
    "Compound existential risk",
    "Decisive strategic advantage",
    "Defense in depth",
    "Differential progress",
    "Estimation of existential risk",
    "Existential catastrophe",
    "Existential risk",
    "Existential risk factor",
    "Existential security",
    "Fermi paradox",
    "Flourishing futures",
    "Global catastrophic risk",
    "Global catastrophic biological risk",
    "Great Filter",
    "Hellish existential catastrophe",
    "Hinge of history",
    "Institutions for future generations",
    "Long reflection",
    "Movement resilience",
    "Natural existential risk",
    "Singleton",
    "Speeding up development",
    "Technological completion conjecture",
    "Time of perils hypothesis",
    "Timing of existential risk mitigation",
    "Total existential risk",
    "Trajectory changes",
    "Transformative development",
    "Transhumanism",
    "Unknown existential risk",
    "Unprecedented risks",
    "Vulnerable world hypothesis",
    "Warning shot",
]


decision_theory_and_rationality = [
    "Acausal trade",
    "Alternatives to expected value theory",
    "Altruistic coordination",
    "Altruistic wager",
    "Anthropics",
    "Bayesian epistemology",
    "Cause neutrality",
    "Cause prioritization",
    "Cognitive bias",
    "Counterfactual reasoning",
    "Credal resilience",
    "Crucial consideration",
    "Debunking argument",
    "Decision theory",
    "Definition of effective altruism",
    "Disentanglement research",
    "Doomsday argument",
    "Epistemic deference",
    "Epistemology",
    "Evolution heuristic",
    "Expected value",
    "Fanaticism",
    "Fermi estimation",
    "Forecasting",
    "Game theory",
    "Ideological Turing test",
    "Information hazard",
    "Intervention evaluation",
    "Macrostrategy",
    "Marginal charity",
    "Measuring and comparing value",
    "Model uncertainty",
    "Models",
    "Moral cooperation",
    "Moral psychology",
    "Moral trade",
    "Prediction markets",
    "Principle of epistemic deference",
    "Psychology research",
    "Randomized controlled trials",
    "Research methods",
    "Reversal test",
    "Risk aversion",
    "Scope neglect",
    "Simulation argument",
    "Statistical methods",
    "Status quo bias",
    "Thinking at the margin",
    "Value of information",
]

economics_and_finance = [
    "Adjusted life year",
    "Blockchain",
    "Divestment",
    "Economics",
    "Impact investing",
    "International trade",
    "Macroeconomic policy",
    "Mechanism design",
    "Microfinance",
    "Public goods",
    "Welfare economics",
]

politics_policy_and_culture = [
"Ballot initiative",
"Corruption",
"Cultural evolution",
"Cultural lag",
"Cultural persistence",
"Democracy",
"Electoral politics",
"Global governance",
"International organization",
"International relations",
"Journalism",
"Law",
"Leadership",
"Misinformation",
"Peace and conflict studies",
"Polarity",
"Policy",
"Political polarization",
"Progress studies",
"Safeguarding liberal democracy",
"Social and intellectual movements",
"Space governance",
"Systemic change",
"Surveillance",
"Totalitarianism",
]

effective_giving = [
    "Cash transfers",
    "Certificate of impact",
    "Charity evaluation",
    "Constraints on effective altruism",
    "Diminishing returns",
    "Donation choice",
    "Donation matching",
    "Donation pledge",
    "Donation writeup",
    "Donor lotteries",
    "Effective altruism funding",
    "Giving and happiness",
    "Impact assessment",
    "Importance",
    "Interpersonal comparisons of wellbeing",
    "Investing",
    "ITN framework",
    "Market efficiency of philanthropy",
    "Markets for altruism",
    "Neglectedness",
    "Org strategy",
    "Philanthropic coordination",
    "Philanthropic diversification",
    "Problem framework",
    "Room for more funding",
    "Socially responsible investing",
    "Temporal discounting",
    "Timing of philanthropy",
    "Tractability",
    "Volunteering",
    "Workplace activism",
]

career_choice = [
    "Academia",
    "Career advising",
    "Career capital",
    "Career choice",
    "Career framework",
    "Coaching",
    "Data science",
    "Earning to give",
    "Effective altruism hiring",
    "Entrepreneurship",
    "Expertise",
    "Independent research",
    "Job profile",
    "Job satisfaction",
    "Operations",
    "Personal fit",
    "Public interest technology",
    "Replaceability",
    "Research careers",
    "Research training programs",
    "Role impact",
    "Software engineering",
    "Supportive conditions",
]

other = [
    "Ambition",
    "Atomically precise manufacturing",
    "Biotechnology",
    "China",
    "Computational power of the human brain",
    "Computronium",
    "Corruption",
    "Cryonics",
    "European Union",
    "Extraterrestrial intelligence",
    "Fabianism",
    "Gene drives",
    "History",
    "India",
    "Information security",
    "Iterated embryo selection",
    "Kidney donation",
    "Life sciences",
    "Medicine",
    "North Korea",
    "Obituary",
    "Philippines",
    "Philosophic Radicals",
    "Rationality community",
    "Red teaming",
    "Religion",
    "Russia",
    "Scientific progress",
    "Semiconductors",
    "Ukraine",
    "United States politics",
    "Utilitarian Society",
    "Transparency",
]

criticism = [
    "Criticism of effective altruist causes",
    "Criticism of effective altruism",
    "Criticism of effective altruist organizations",
]

tag_types = {
    "Cause Areas": {
        "Global Poverty": global_poverty,
        "Animal Welfare": animal_welfare,
        "AI": ai,
        "Catastrophic Risks": catastrophic_risks,
        "EA Meta": ea_meta,
        "other causes": other_causes
    },
    "Other concepts": {
        "Moral Philosophy": moral_philosophy,
        "long_term_risks_and_flourising": long_term_risks_and_flourising,
        "decision_theory_and_rationality": decision_theory_and_rationality,
        "economics_and_finance": economics_and_finance,
        "politics_policy_and_culture": politics_policy_and_culture,
        "effective_giving": effective_giving,
        "career_choice": career_choice,
        "other": other
    },
    "Meta + Commmunity": {
        "criticism": criticism,
    }
}

