
# scraped from following url:           https://forum.effectivealtruism.org/tags/all
# using this regex on each html list:   ">([a-zA-Z\s]*)<

global_poverty = ["Aid and paternalism",
"Burden of disease",
"Cash transfers",
"Deworming",
"Economic growth",
"Education",
"Family planning",
"Foreign aid",
"Foreign aid skepticism",
"Global health and wellbeing",
"Global poverty",
"Immigration reform",
"Malaria",
"Micronutrient programs",
"Research into neglected tropical diseases",
"Smallpox Eradication Programme",
"Tobacco control",
"Universal basic income"]

animal_welfare = ["Animal product alternatives",
"Crustacean welfare",
"Cultured meat",
"Dietary change",
"Farmed animal welfare",
"Fish welfare",
"Invertebrate welfare",
"Logic of the larder",
"Speciesism",
"Welfare biology",
"Wild animal welfare"]

ai = ["AI alignment",
"AI boxing",
"AI ethics",
"AI forecasting",
"AI race",
"AI safety",
"AI skepticism",
"AI takeoff",
"AI winter",
"Alignment tax",
"Anthropic capture",
"Artificial intelligence",
"Artificial sentience",
"Basic AI drive",
"Capability control method",
"Collective superintelligence",
"Comprehensive AI Services",
"Computation hazard",
"Economics of artificial intelligence",
"Governance of artificial intelligence",
"Indirect normativity",
"Infrastructure profusion",
"Instrumental convergence thesis",
"Intelligence explosion",
"Malignant AI failure mode",
"Mind crime",
"Motivation selection method",
"Oracle AI",
"Orthogonality thesis",
"Perverse instantiation",
"Quality superintelligence",
"Sovereign AI",
"Speed superintelligence",
"Superintelligence",
"Tool AI",
"Whole brain emulation"]

catastrophic_risks = ["Asteroids",
"Biosecurity",
"Biosurveillance",
"Civilizational collapse",
"Cuban Missile Crisis",
"Climate change",
"Climate engineering",
"Conservation",
"Dystopia",
"Existential risks from fundamental physics research",
"Geomagnetic storms",
"Great power conflict",
"Human extinction",
"Manhattan Project",
"Nuclear disarmament movement",
"Nuclear security",
"Nuclear warfare",
"Nuclear winter",
"Pandemic preparedness",
"Terrorism",
"Trinity",
"Supervolcano",
"Weapons of mass destruction"]

ea_meta = [
"Altruistic motivation",
"Building effective altruism",
"Community",
"Competitive debating",
"Consultancy",
"Effective altruism education",
"Effective altruism groups",
"Effective altruism in the media",
"Effective altruism messaging",
"Effective altruism outreach in schools",
"Event strategy",
"Field building",
"Fundraising",
"Global outreach",
"Moral advocacy",
"Movement collapse",
"Network building",
"Public giving",
"Request for proposal",
"Scalably using labour",
"Teaching materials",
"Value drift",
"Value of movement growth"]

other_causes = [
"Aging research",
"Air pollution",
"Armed conflict",
"Autonomous weapon",
"Cause candidates",
"Cause X",
"Cluster headache",
"Cognitive enhancement",
"Criminal justice reform",
"Electoral reform",
"Global priorities research",
"Land use reform",
"Local priorities research",
"Mental health",
"Moral circle expansion",
"Research",
"Risks from malevolent actors",
"Space colonization"]

tag_types = {
    "Global Poverty": global_poverty,
    "Animal Welfare": animal_welfare,
    "AI": ai,
    "Catastrophic Risks": catastrophic_risks,
    "EA Meta": ea_meta,
    "other causes": other_causes
}